# Generated by Django 2.2.9 on 2020-02-27 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200227_1034'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='board_task', to='boards.Board'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='task_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task_comment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task_comment',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_comment', to='tasks.Task'),
        ),
        migrations.AddField(
            model_name='task_history',
            name='task',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_history', to='tasks.Task'),
        ),
    ]
