# Generated by Django 2.2.9 on 2020-02-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200227_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
