# Generated by Django 2.2.9 on 2020-02-27 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0002_board_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='board_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='boards_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board_comment',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='board_comment', to='boards.Board'),
        ),
        migrations.AddField(
            model_name='board_comment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='board_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
