# Generated by Django 2.2.9 on 2020-02-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20200227_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
